name-template: v$RESOLVED_VERSION 🏳️‍🌈
tag-template: v$RESOLVED_VERSION
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
categories:
  - title: ⚠️ Breaking changes
    labels: [":warning: breaking change"]
  - title: 🚀 Features
    labels: [":rocket: feature"]
  - title: 🔧 Code enhancements
    labels: [":wrench: enhancement"]
  - title: 🐛 Bug Fixes
    labels: [":bug: bug"]
  - title: 💬 Translations
    labels: [":speech_balloon: translation"]
  - title: 📝 Documentation
    labels: [":memo: documentation"]
  - title: 🎲 Dependencies
    labels: [":game_die: dependencies"]
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES

  ## ❤️ Thank you so much for helping out to keep this project awesome
  $CONTRIBUTORS

exclude-contributors:
  - github-actions

autolabeler:
  - label: ":bug: bug"
    branch:
      - /fix/.+/
  - label: ":bulb: feature"
    branch:
      - /feature/.+/
