repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
        exclude: .devcontainer
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '120', --implicit_start]
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: poetry run codespell --write-changes --skip="./*"
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]
      - id: ruff lint
        name: ruff lint
        entry: poetry run ruff
        language: system
        types: [python]
