[tool.poetry]
name = "qss"
version = "0.0.1"
description = "QuestDB State Storage (QSS) for Home Assistant"
license = "MIT"
readme = "README.md"
authors = ["CM000n"]


[tool.poetry.dependencies]
python = "~3.9.2"
homeassistant = "^2022.12"
questdb = "^1.0.2"
tenacity = "^5.0.3"


[tool.poetry.dev-dependencies]
pre-commit = "^2.21.0"
black = "^22.12.0"
ruff = "^0.0.246"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    "YTT",
    # Isort
    "I001",
    "I002"
]
line-length = 88
fix = true
