[tool.poetry]
name = "QSS"
version = "0"
description = "QuestDB State Storage (QSS) for Home Assistant"
license = "MIT"
readme = "README.md"
authors = ["CM000n"]


[tool.poetry.dependencies]
python = "~3.9.2"
questdb = "^1.0.2"


[tool.poetry.dev-dependencies]
PyJWT = "^2.5.0"
PyNaCl = "^1.5.0"
aiodiscover = "^1.4.13"
aiohttp = "^3.8.1"
aiohttp_cors = "^0.7.0"
astral = "^2.2"
async-upnp-client = "^0.33.0"
async_timeout = "^4.0.2"
atomicwrites-homeassistant = "^1.4.1"
attrs = "^22.1.0"
awesomeversion = "^22.9.0"
bcrypt = "^3.1.7"
bleak-retry-connector = "^2.10.2"
bleak = "^0.19.2"
bluetooth-adapters = "^0.14.1"
bluetooth-auto-recovery = "^1.0.3"
bluetooth-data-tools = "^0.3.1"
certifi = "^2021.5.30"
ciso8601 = "^2.3.0"
cryptography = "^38.0.3"
dbus-fast = "^1.82.0"
fnvhash = "^0.1.0"
hass-nabucasa = "^0.61.0"
home-assistant-bluetooth = "^1.9.0"
home-assistant-frontend = "^20221213.1"
httpx = "^0.23.1"
ifaddr = "^0.1.7"
janus = "^1.0.0"
jinja2 = "^3.1.2"
lru-dict = "^1.1.8"
orjson = "^3.8.1"
paho-mqtt = "^1.6.1"
pillow = "^9.3.0"
psutil-home-assistant = "^0.0.1"
pyserial = "^3.5"
python-slugify = "^4.0.1"
pyudev = "^0.23.2"
pyyaml = "^6.0"
requests = "^2.28.1"
scapy = "^2.4.5"
sqlalchemy = "^1.4.44"
typing-extensions = "^4.4.0"
voluptuous-serialize = "^2.5.0"
voluptuous = "^0.13.1"
yarl = "^1.8.1"
zeroconf = "^0.47.0"
pycryptodome = "^3.6.6"
urllib3 = "^1.26.5"
httplib2 = "^0.19.0"
grpcio = "^1.51.1"
grpcio-status = "^1.51.1"
libcst = "^0.3.23"
btlewrap = "^0.0.10"
regex = "^2021.8.28"
anyio = "^3.6.2"
h11 = "^0.14.0"
httpcore = "^0.16.2"
hyperframe = "^5.2.0"
numpy = "^1.23.2"
multidict = "^6.0.2"
authlib = "^1.0"
backoff = "^2.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
