[tool.poetry]
name = "qss"
version = "v0.0.6"
description = "QuestDB State Storage (QSS) for Home Assistant"
license = "MIT"
readme = "README.md"
authors = ["CM000n"]


[tool.poetry.dependencies]
python = "^3.10.0"
questdb = "^1.0.2"
tenacity = "^8.0.0"


[tool.poetry.dev-dependencies]
homeassistant = "^2023.6"
pre-commit = "^2.21.0"
black = "^22.12.0"
ruff = "^0.1.6"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    "YTT",
    # Isort
    "I001",
    "I002"
]
line-length = 88
fix = false
