name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
